### ISSUE TITLE
test_input.json is required

### ISSUE THREAD

**Issue by wwydmanski** [runpod-workers/worker-vllm#31]
When I try to run the worker, I'm getting the following error:
`WARN   | test_input.json not found, exiting.`

which prevents me from using the runpod worker.

**Comment by alpayariyak** [comment]
Hi @wwydmanski, could you please share more details? Does this still persist?

**Comment by ashleykleynhans** [comment]
This is normal when you run it locally, you can start the local API as follows:
```bash
python3 -u handler.py --rp_serve_api --rp_api_port 8000 --rp_api_host 0.0.0.0
```
Otherwise it defaults to looking for `test_input.json` instead.

**Comment by dpkirchner** [comment]
For future readers, the non-vllm workers can be tested with the `--test-input '{"input": {"message": "blah"}}'` flag, but for vllm you need to put that input object in a `test_input.json` file in your current working directory.

(This isn't actually sufficient because the worker just outputs `async_generator object handler at ...` stuff, but it'll help you deal with this specific error message.)
